#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

$kernel = new \App\Kernel\Kernel();
/** @var \Silly\Application $app */
$app = $kernel->boot()->getContainer()->get(\Silly\Application::class);

$app->run();
